kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-microsi-postgresql-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
